<?php

namespace Database\Seeders;

use App\Models\Stock;
use Illuminate\Database\Seeder;

class StockSeeder extends Seeder
{
    public function run(): void
    {
        $stocks = [
            [
                'symbol' => 'RELIANCE',
                'company_name' => 'Reliance Industries Ltd.',
                'sector' => 'Conglomerate',
                'price' => 2890.50,
                'previous_price' => 2850.00,
                'change_percentage' => 1.42,
                'market_cap' => 19560000000000,
                'volume' => 4500000,
                'is_trending' => true,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'TCS',
                'company_name' => 'Tata Consultancy Services',
                'sector' => 'Information Technology',
                'price' => 3890.75,
                'previous_price' => 3920.00,
                'change_percentage' => -0.75,
                'market_cap' => 14200000000000,
                'volume' => 3200000,
                'is_trending' => true,
                'is_top_gainer' => false,
                'is_top_loser' => true,
            ],
            [
                'symbol' => 'HDFCBANK',
                'company_name' => 'HDFC Bank Ltd.',
                'sector' => 'Banking',
                'price' => 1670.25,
                'previous_price' => 1645.00,
                'change_percentage' => 1.53,
                'market_cap' => 9350000000000,
                'volume' => 5600000,
                'is_trending' => true,
                'is_top_gainer' => true,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'INFY',
                'company_name' => 'Infosys Ltd.',
                'sector' => 'Information Technology',
                'price' => 1520.60,
                'previous_price' => 1540.00,
                'change_percentage' => -1.26,
                'market_cap' => 6450000000000,
                'volume' => 4100000,
                'is_trending' => true,
                'is_top_gainer' => false,
                'is_top_loser' => true,
            ],
            [
                'symbol' => 'ICICIBANK',
                'company_name' => 'ICICI Bank Ltd.',
                'sector' => 'Banking',
                'price' => 1120.30,
                'previous_price' => 1095.00,
                'change_percentage' => 2.31,
                'market_cap' => 7850000000000,
                'volume' => 3800000,
                'is_trending' => true,
                'is_top_gainer' => true,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'BHARTIARTL',
                'company_name' => 'Bharti Airtel Ltd.',
                'sector' => 'Telecommunications',
                'price' => 1280.45,
                'previous_price' => 1260.00,
                'change_percentage' => 1.62,
                'market_cap' => 7150000000000,
                'volume' => 2900000,
                'is_trending' => true,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'SBIN',
                'company_name' => 'State Bank of India',
                'sector' => 'Banking',
                'price' => 785.90,
                'previous_price' => 795.00,
                'change_percentage' => -1.14,
                'market_cap' => 7020000000000,
                'volume' => 6200000,
                'is_trending' => false,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'WIPRO',
                'company_name' => 'Wipro Ltd.',
                'sector' => 'Information Technology',
                'price' => 490.20,
                'previous_price' => 485.00,
                'change_percentage' => 1.07,
                'market_cap' => 2780000000000,
                'volume' => 3500000,
                'is_trending' => false,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'HINDUNILVR',
                'company_name' => 'Hindustan Unilever Ltd.',
                'sector' => 'Consumer Goods',
                'price' => 2560.80,
                'previous_price' => 2580.00,
                'change_percentage' => -0.74,
                'market_cap' => 6020000000000,
                'volume' => 1800000,
                'is_trending' => false,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'ITC',
                'company_name' => 'ITC Ltd.',
                'sector' => 'Consumer Goods',
                'price' => 445.35,
                'previous_price' => 438.00,
                'change_percentage' => 1.68,
                'market_cap' => 5580000000000,
                'volume' => 4200000,
                'is_trending' => true,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'LT',
                'company_name' => 'Larsen & Toubro Ltd.',
                'sector' => 'Construction',
                'price' => 3680.15,
                'previous_price' => 3650.00,
                'change_percentage' => 0.83,
                'market_cap' => 5120000000000,
                'volume' => 2100000,
                'is_trending' => false,
                'is_top_gainer' => false,
                'is_top_loser' => false,
            ],
            [
                'symbol' => 'TATAMOTORS',
                'company_name' => 'Tata Motors Ltd.',
                'sector' => 'Automobile',
                'price' => 985.60,
                'previous_price' => 970.00,
                'change_percentage' => 1.61,
                'market_cap' => 3250000000000,
                'volume' => 4800000,
                'is_trending' => true,
                'is_top_gainer' => true,
                'is_top_loser' => false,
            ],
        ];

        foreach ($stocks as $stock) {
            Stock::create($stock);
        }
    }
}
